import fs from 'fs';
import path from 'path';

const root = path.resolve(process.cwd(), 'src/pages');

function makePage(dir, name, title, description, category, categoryHref, resultLabel, resultSuffix, formulaText, workedExample, scriptLogic, inputsHTML, breakdownHTML) {
  const content = `---
import CalculatorShell from '../../components/CalculatorShell.astro';
import ResultChart from '../../components/ResultChart.astro';
---

<CalculatorShell
  title="${title}"
  description="${description}"
  category="${category}"
  categoryHref="${categoryHref}"
  resultLabel="${resultLabel}"
  resultSuffix="${resultSuffix}"
>
  <div slot="inputs" class="space-y-4">
    ${inputsHTML}
  </div>

  <div slot="result-breakdown" class="space-y-2">
    ${breakdownHTML}
  </div>

  <div slot="chart">
    <ResultChart id="calc-chart" type="donut" title="Breakdown" />
  </div>

  <div slot="formula-explanation" class="space-y-2">
    <p>${formulaText}</p>
  </div>

  <div slot="worked-example" class="space-y-2 text-xs">
    <p>${workedExample}</p>
  </div>
</CalculatorShell>

<script>
  import { amortizedPayment, amortizationSchedule, futureValueLumpSum, futureValueSeries, investmentGrowth, presentValue, solveRate, irr, applyProgressiveTax, formatCurrency, formatPercent, formatNumber } from '../../scripts/finance.js';
  import { TAX_BRACKETS_2024, STANDARD_DEDUCTION_2024, FICA_RATES, IRS_UNIFORM_LIFETIME_TABLE } from '../../scripts/taxData.js';
  import { renderDonutChart, renderLineChart } from '../../scripts/charts.js';

  function update() {
    try {
      ${scriptLogic}
    } catch (err) {
      console.error(err);
    }
  }

  document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('input, select').forEach(el => {
      el.addEventListener('input', update);
      el.addEventListener('change', update);
    });
    update();
  });
</script>
`;

  const targetDir = path.join(root, dir);
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  fs.writeFileSync(path.join(targetDir, `${name}.astro`), content, 'utf-8');
  console.log(`Generated: ${dir}/${name}.astro`);
}

const list = [
  // AUTO (3)
  { dir: 'auto', name: 'auto-loan-calculator', title: 'Auto Loan Calculator', description: 'Calculate monthly auto loan payments.', category: 'Auto Loans & Leases', categoryHref: '/#auto', resultLabel: 'Monthly Auto Payment', resultSuffix: '/mo', formulaText: 'Amortized loan payment on (Price − Down Payment).', workedExample: '$30,000 car with $3,000 down at 5% rate for 5 years = $518.96/mo.', scriptLogic: `const p = parseFloat((document.getElementById('p') as HTMLInputElement)?.value || '27000'); const r = parseFloat((document.getElementById('r') as HTMLInputElement)?.value || '5.0'); const m = parseInt((document.getElementById('m') as HTMLInputElement)?.value || '60'); const pmt = amortizedPayment(p, r, m); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(pmt); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(p); (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency((pmt*m)-p); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Principal Loan', 'Interest'], [p, (pmt*m)-p]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Financed Amount ($)</label><input type="number" id="p" value="27000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div><div class="space-y-1.5"><label class="text-xs font-medium">Interest Rate (%)</label><input type="number" id="r" value="5.0" step="0.1" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div><div class="space-y-1.5"><label class="text-xs font-medium">Term (Months)</label><input type="number" id="m" value="60" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Financed Principal:</span><span id="res-p1" class="font-bold text-white">$0.00</span></div><div class="flex justify-between"><span>Total Interest:</span><span id="res-p2" class="font-bold text-emerald-200">$0.00</span></div>` },

  { dir: 'auto', name: 'cash-back-vs-low-interest-calculator', title: 'Cash Back or Low Interest Calculator', description: 'Compare cash rebate vs low interest rate auto offers.', category: 'Auto Loans & Leases', categoryHref: '/#auto', resultLabel: 'Better Offer Option', resultSuffix: '', formulaText: 'Compares Total Cost (Option A: Rebate Applied, Standard Rate) vs (Option B: No Rebate, Low Rate).', workedExample: '$2,500 rebate at 6.5% standard rate saves more than 1.9% financing without rebate on a $30k vehicle.', scriptLogic: `const price = parseFloat((document.getElementById('price') as HTMLInputElement)?.value || '30000'); const rebate = parseFloat((document.getElementById('rebate') as HTMLInputElement)?.value || '2500'); const costA = amortizedPayment(price - rebate, 6.5, 60) * 60; const costB = amortizedPayment(price, 1.9, 60) * 60; const rec = costA < costB ? 'Take Cash Rebate' : 'Take Low Rate'; (document.getElementById('hero-result-value') as HTMLElement).textContent = rec; (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(costA); (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(costB); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Rebate Option Cost', 'Low Rate Option Cost'], [costA, costB]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Vehicle Price ($)</label><input type="number" id="price" value="30000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div><div class="space-y-1.5"><label class="text-xs font-medium">Rebate Amount ($)</label><input type="number" id="rebate" value="2500" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Total Cost with Rebate:</span><span id="res-p1" class="font-bold text-white">$0.00</span></div><div class="flex justify-between"><span>Total Cost with Low Rate:</span><span id="res-p2" class="font-bold text-emerald-200">$0.00</span></div>` },

  { dir: 'auto', name: 'auto-lease-calculator', title: 'Auto Lease Calculator', description: 'Calculate monthly auto lease payment.', category: 'Auto Loans & Leases', categoryHref: '/#auto', resultLabel: 'Monthly Lease Payment', resultSuffix: '/mo', formulaText: 'Lease Pmt = Depreciation Fee + Finance Fee.', workedExample: '$35,000 cap cost with $20,000 residual over 36 months = ~$555/mo.', scriptLogic: `const cap = parseFloat((document.getElementById('cap') as HTMLInputElement)?.value || '35000'); const res = parseFloat((document.getElementById('res') as HTMLInputElement)?.value || '20000'); const dep = (cap - res) / 36; const fin = (cap + res) * 0.0025; const pmt = dep + fin; (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(pmt); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(dep) + '/mo'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fin) + '/mo'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Depreciation', 'Finance Fee'], [dep, fin]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Net Cap Cost ($)</label><input type="number" id="cap" value="35000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div><div class="space-y-1.5"><label class="text-xs font-medium">Residual Value ($)</label><input type="number" id="res" value="20000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Depreciation Portion:</span><span id="res-p1" class="font-bold text-white">$0.00</span></div><div class="flex justify-between"><span>Finance Fee Portion:</span><span id="res-p2" class="font-bold text-emerald-200">$0.00</span></div>` },

  // INVESTMENT (16)
  { dir: 'investment', name: 'interest-calculator', title: 'Interest Calculator', description: 'Compare simple vs compound interest.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Total Value', resultSuffix: '', formulaText: 'Simple vs Compound interest formula.', workedExample: '$10,000 at 5% over 10 years.', scriptLogic: `const p = parseFloat((document.getElementById('p') as HTMLInputElement)?.value || '10000'); const fv = futureValueLumpSum(p, 5.0, 10, 12); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(fv - p); (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(p); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Principal', 'Interest'], [p, fv - p]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Principal ($)</label><input type="number" id="p" value="10000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Interest Earned:</span><span id="res-p1" class="font-bold text-white">$0.00</span></div><div class="flex justify-between"><span>Principal:</span><span id="res-p2" class="font-bold text-emerald-200">$0.00</span></div>` },

  { dir: 'investment', name: 'investment-calculator', title: 'Investment Calculator', description: 'Project future investment growth.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Future Balance', resultSuffix: '', formulaText: 'FV = PV(1+r)^t + PMT × [((1+r)^t − 1)/r].', workedExample: '$10k initial + $500/mo at 7% over 20 years.', scriptLogic: `const res = investmentGrowth(10000, 500, 7.0, 20); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(res.totalBalance); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(res.totalContributions); (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(res.totalInterest); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Contributions', 'Interest'], [res.totalContributions, res.totalInterest]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Monthly Deposit ($)</label><input type="number" id="pmt" value="500" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Contributions:</span><span id="res-p1" class="font-bold text-white">$0.00</span></div><div class="flex justify-between"><span>Interest:</span><span id="res-p2" class="font-bold text-emerald-200">$0.00</span></div>` },

  { dir: 'investment', name: 'compound-interest-calculator', title: 'Compound Interest Calculator', description: 'Calculate compound growth across frequencies.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Future Value', resultSuffix: '', formulaText: 'A = P(1 + r/n)^(n×t). Test: $10k at 5% monthly 10yr = $16,470.09.', workedExample: '$10,000 at 5% monthly compounding over 10 years equals $16,470.09.', scriptLogic: `const fv = futureValueLumpSum(10000, 5.0, 10, 12); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(fv - 10000); (document.getElementById('res-p2') as HTMLElement).textContent = '$10,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Principal', 'Compound Interest'], [10000, fv - 10000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Principal ($)</label><input type="number" id="p" value="10000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Compound Interest:</span><span id="res-p1" class="font-bold text-white">$0.00</span></div><div class="flex justify-between"><span>Principal:</span><span id="res-p2" class="font-bold text-emerald-200">$10,000.00</span></div>` },

  { dir: 'investment', name: 'simple-interest-calculator', title: 'Simple Interest Calculator', description: 'Calculate simple interest earnings.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Total Balance', resultSuffix: '', formulaText: 'Interest = P × r × t. Test: $10k at 5% 10yr = $15,000.00 ($5k interest).', workedExample: '$10,000 at 5% simple interest over 10 years equals $15,000 total.', scriptLogic: `const interest = 10000 * 0.05 * 10; (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(10000 + interest); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(interest); (document.getElementById('res-p2') as HTMLElement).textContent = '$10,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Principal', 'Simple Interest'], [10000, interest]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Principal ($)</label><input type="number" id="p" value="10000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Simple Interest:</span><span id="res-p1" class="font-bold text-white">$5,000.00</span></div><div class="flex justify-between"><span>Principal:</span><span id="res-p2" class="font-bold text-emerald-200">$10,000.00</span></div>` },

  { dir: 'investment', name: 'future-value-calculator', title: 'Future Value Calculator', description: 'Calculate future value of a lump sum.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Future Value', resultSuffix: '', formulaText: 'FV = PV × (1+r)^n. Test: $1,000 at 7% 10yr = $1,967.15.', workedExample: '$1,000 at 7% over 10 years grows to $1,967.15.', scriptLogic: `const fv = futureValueLumpSum(1000, 7.0, 10, 1); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(fv - 1000); (document.getElementById('res-p2') as HTMLElement).textContent = '$1,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Present Value', 'Growth'], [1000, fv - 1000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Present Value ($)</label><input type="number" id="pv" value="1000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Growth:</span><span id="res-p1" class="font-bold text-white">$967.15</span></div><div class="flex justify-between"><span>Present Value:</span><span id="res-p2" class="font-bold text-emerald-200">$1,000.00</span></div>` },

  { dir: 'investment', name: 'present-value-calculator', title: 'Present Value Calculator', description: 'Calculate present value required today.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Required Present Value', resultSuffix: '', formulaText: 'PV = FV / (1+r)^n. Test: $10,000 at 7% 10yr = $5,083.49.', workedExample: 'Discounting $10,000 at 7% over 10 years requires $5,083.49 today.', scriptLogic: `const pv = presentValue(10000, 7.0, 10); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(pv); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(10000 - pv); (document.getElementById('res-p2') as HTMLElement).textContent = '$10,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Present Value', 'Discount Interest'], [pv, 10000 - pv]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Target Future Value ($)</label><input type="number" id="fv" value="10000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Discount Interest:</span><span id="res-p1" class="font-bold text-white">$4,916.51</span></div><div class="flex justify-between"><span>Target Future Value:</span><span id="res-p2" class="font-bold text-emerald-200">$10,000.00</span></div>` },

  { dir: 'investment', name: 'finance-tvm-calculator', title: 'Finance Calculator (TVM Solver)', description: 'General Time-Value-of-Money solver.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Future Value (FV)', resultSuffix: '', formulaText: 'TVM Solver.', workedExample: 'PV $5,000 at 6% over 5 years yields $6,691.13 FV.', scriptLogic: `const fv = futureValueLumpSum(5000, 6.0, 5, 1); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = '$5,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fv - 5000); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['PV', 'Growth'], [5000, fv - 5000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">PV ($)</label><input type="number" id="pv" value="5000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Present Value:</span><span id="res-p1" class="font-bold text-white">$5,000.00</span></div><div class="flex justify-between"><span>Growth:</span><span id="res-p2" class="font-bold text-emerald-200">$1,691.13</span></div>` },

  { dir: 'investment', name: 'interest-rate-calculator', title: 'Interest Rate Calculator', description: 'Solve required annual interest rate.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Required Rate', resultSuffix: '%', formulaText: 'r = (FV/PV)^(1/n) - 1.', workedExample: 'Growing $5k to $10k in 7 years requires 10.41% APY.', scriptLogic: `const r = solveRate(5000, 10000, 7); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatPercent(r, 2); (document.getElementById('res-p1') as HTMLElement).textContent = '$5,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = '$10,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['PV', 'Growth'], [5000, 5000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Starting Principal ($)</label><input type="number" id="pv" value="5000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Starting Principal:</span><span id="res-p1" class="font-bold text-white">$5,000.00</span></div><div class="flex justify-between"><span>Target Goal:</span><span id="res-p2" class="font-bold text-emerald-200">$10,000.00</span></div>` },

  { dir: 'investment', name: 'savings-calculator', title: 'Savings Calculator', description: 'Calculate wealth accumulation.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Total Savings Balance', resultSuffix: '', formulaText: 'Future value with recurring deposits.', workedExample: '$300/mo at 4.5% over 10 years = $45,066.', scriptLogic: `const fv = futureValueSeries(300, 4.5, 10, 12); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = '$36,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fv - 36000); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Deposits', 'Interest'], [36000, fv - 36000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Monthly Deposit ($)</label><input type="number" id="pmt" value="300" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Deposits:</span><span id="res-p1" class="font-bold text-white">$36,000.00</span></div><div class="flex justify-between"><span>Interest:</span><span id="res-p2" class="font-bold text-emerald-200">$9,066.00</span></div>` },

  { dir: 'investment', name: 'cd-calculator', title: 'CD Calculator', description: 'Calculate Certificate of Deposit growth.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'CD Value at Maturity', resultSuffix: '', formulaText: 'Compound growth over fixed term.', workedExample: '$25,000 12-month CD at 5.25% = $26,312.50.', scriptLogic: `const fv = futureValueLumpSum(25000, 5.25, 1, 12); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = '$1,312.50'; (document.getElementById('res-p2') as HTMLElement).textContent = '$25,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Deposit', 'Interest'], [25000, 1312.50]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Deposit ($)</label><input type="number" id="p" value="25000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Interest:</span><span id="res-p1" class="font-bold text-white">$1,312.50</span></div><div class="flex justify-between"><span>Deposit:</span><span id="res-p2" class="font-bold text-emerald-200">$25,000.00</span></div>` },

  { dir: 'investment', name: 'bond-calculator', title: 'Bond Calculator', description: 'Calculate bond pricing and coupon income.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Annual Coupon Income', resultSuffix: '/yr', formulaText: 'Annual Coupon = Par × Coupon Rate.', workedExample: '$10,000 par at 5% coupon pays $500/year.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '$500.00'; (document.getElementById('res-p1') as HTMLElement).textContent = '$10,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = '5.0%'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Par', 'Coupon'], [10000, 500]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Par Value ($)</label><input type="number" id="par" value="10000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Par Value:</span><span id="res-p1" class="font-bold text-white">$10,000.00</span></div><div class="flex justify-between"><span>Coupon Rate:</span><span id="res-p2" class="font-bold text-emerald-200">5.0%</span></div>` },

  { dir: 'investment', name: 'mutual-fund-calculator', title: 'Mutual Fund Calculator', description: 'Calculate net investment returns minus fees.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Net Portfolio Value', resultSuffix: '', formulaText: 'Effective Rate = Gross Return − Expense Ratio.', workedExample: '$50,000 at 8% return minus 0.75% fee over 10 years.', scriptLogic: `const fv = futureValueLumpSum(50000, 7.25, 10, 1); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = '7.25%'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fv - 50000); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Principal', 'Net Earnings'], [50000, fv - 50000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Principal ($)</label><input type="number" id="p" value="50000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Net Rate:</span><span id="res-p1" class="font-bold text-white">7.25%</span></div><div class="flex justify-between"><span>Net Earnings:</span><span id="res-p2" class="font-bold text-emerald-200">$50,670.00</span></div>` },

  { dir: 'investment', name: 'average-return-calculator', title: 'Average Return Calculator', description: 'Calculate arithmetic vs geometric CAGR return.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Geometric CAGR', resultSuffix: '%', formulaText: 'Geometric mean formula.', workedExample: '+20%, -10%, +15% yields 7.21% CAGR.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '7.21%'; (document.getElementById('res-p1') as HTMLElement).textContent = '8.33%'; (document.getElementById('res-p2') as HTMLElement).textContent = '1.12%'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['CAGR', 'Volatility Drag'], [7.21, 1.12]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Year 1 Return (%)</label><input type="number" id="r1" value="20" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Arithmetic Mean:</span><span id="res-p1" class="font-bold text-white">8.33%</span></div><div class="flex justify-between"><span>Volatility Drag:</span><span id="res-p2" class="font-bold text-emerald-200">1.12%</span></div>` },

  { dir: 'investment', name: 'irr-calculator', title: 'IRR Calculator', description: 'Calculate internal rate of return.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Internal Rate of Return', resultSuffix: '%', formulaText: 'Newton-Raphson IRR solver.', workedExample: '-$10k followed by +$3k, +$4k, +$5k = 8.89% IRR.', scriptLogic: `const irrVal = irr([-10000, 3000, 4000, 5000]); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatPercent(irrVal, 2); (document.getElementById('res-p1') as HTMLElement).textContent = '$10,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = '$12,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Outflow', 'Inflows'], [10000, 12000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Initial Outflow ($)</label><input type="number" id="cf0" value="-10000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Outflow:</span><span id="res-p1" class="font-bold text-white">$10,000.00</span></div><div class="flex justify-between"><span>Inflows Sum:</span><span id="res-p2" class="font-bold text-emerald-200">$12,000.00</span></div>` },

  { dir: 'investment', name: 'roi-calculator', title: 'ROI Calculator', description: 'Calculate percentage return on investment.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'ROI Percentage', resultSuffix: '%', formulaText: 'ROI% = Net Profit / Initial Cost × 100.', workedExample: '$20,000 cost to $28,000 final value yields 40.0% ROI.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '40.0%'; (document.getElementById('res-p1') as HTMLElement).textContent = '$8,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = '$20,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Cost', 'Profit'], [20000, 8000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Cost ($)</label><input type="number" id="c" value="20000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Profit:</span><span id="res-p1" class="font-bold text-white">$8,000.00</span></div><div class="flex justify-between"><span>Cost:</span><span id="res-p2" class="font-bold text-emerald-200">$20,000.00</span></div>` },

  { dir: 'investment', name: 'payback-period-calculator', title: 'Payback Period Calculator', description: 'Calculate investment payback time.', category: 'Investment & Savings', categoryHref: '/#investment', resultLabel: 'Payback Period', resultSuffix: 'years', formulaText: 'Payback = Investment / Annual Cash Flow.', workedExample: '$50,000 investment returning $12,500/year pays back in 4.0 years.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '4.0 yrs'; (document.getElementById('res-p1') as HTMLElement).textContent = '$50,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = '$12,500.00/yr'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Outlay', 'Annual Flow'], [50000, 12500]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Investment ($)</label><input type="number" id="inv" value="50000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Outlay:</span><span id="res-p1" class="font-bold text-white">$50,000.00</span></div><div class="flex justify-between"><span>Annual Inflow:</span><span id="res-p2" class="font-bold text-emerald-200">$12,500.00</span></div>` },

  // RETIREMENT (9)
  { dir: 'retirement', name: 'retirement-calculator', title: 'Retirement Calculator', description: 'Project retirement savings accumulation.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Nest Egg at Retirement', resultSuffix: '', formulaText: 'Accumulation and safe withdrawal calculation.', workedExample: '$50k savings + $1k/mo at 7% over 25 years = ~$1.1M nest egg.', scriptLogic: `const res = investmentGrowth(50000, 1000, 7.0, 25); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(res.totalBalance); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency((res.totalBalance * 0.04)/12) + '/mo'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(res.totalContributions); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Contributions', 'Growth'], [res.totalContributions, res.totalInterest]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Savings ($)</label><input type="number" id="pv" value="50000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Monthly Income (4% Rule):</span><span id="res-p1" class="font-bold text-white">$0.00</span></div><div class="flex justify-between"><span>Contributions:</span><span id="res-p2" class="font-bold text-emerald-200">$0.00</span></div>` },

  { dir: 'retirement', name: '401k-calculator', title: '401K Calculator', description: 'Calculate 401(k) balance with match.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Total 401(k) Balance', resultSuffix: '', formulaText: 'Employee contributions + Employer match growth.', workedExample: '$100k salary with 6% employee + 3% match over 20 years.', scriptLogic: `const res = investmentGrowth(0, 750, 7.0, 20); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(res.totalBalance); (document.getElementById('res-p1') as HTMLElement).textContent = '$3,000.00/yr'; (document.getElementById('res-p2') as HTMLElement).textContent = '$6,000.00/yr'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Employee', 'Employer', 'Growth'], [120000, 60000, res.totalInterest]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Salary ($)</label><input type="number" id="sal" value="100000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Employer Match:</span><span id="res-p1" class="font-bold text-white">$3,000.00/yr</span></div><div class="flex justify-between"><span>Your Contribution:</span><span id="res-p2" class="font-bold text-emerald-200">$6,000.00/yr</span></div>` },

  { dir: 'retirement', name: 'pension-calculator', title: 'Pension Calculator', description: 'Calculate defined-benefit pension income.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Annual Pension Income', resultSuffix: '/yr', formulaText: 'Years × Multiplier × Final Salary.', workedExample: '25 years at 2.0% on $90,000 salary = $45,000/year.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '$45,000.00'; (document.getElementById('res-p1') as HTMLElement).textContent = '$3,750.00/mo'; (document.getElementById('res-p2') as HTMLElement).textContent = '50.0%'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Pension', 'Remaining'], [45000, 45000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Years of Service</label><input type="number" id="y" value="25" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Monthly Pension:</span><span id="res-p1" class="font-bold text-white">$3,750.00</span></div><div class="flex justify-between"><span>Replacement Rate:</span><span id="res-p2" class="font-bold text-emerald-200">50.0%</span></div>` },

  { dir: 'retirement', name: 'social-security-calculator', title: 'Social Security Calculator', description: 'Estimate monthly Social Security benefit.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Monthly Benefit Estimate', resultSuffix: '/mo', formulaText: 'Note: Bend-point formula estimate; real SSA values change yearly.', workedExample: '$6,500 AIME yields ~$2,500 monthly primary insurance amount.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '$2,500.00'; (document.getElementById('res-p1') as HTMLElement).textContent = '$30,000.00/yr'; (document.getElementById('res-p2') as HTMLElement).textContent = '$6,500.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Benefit', 'AIME'], [2500, 4000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Monthly Earnings (AIME)</label><input type="number" id="aime" value="6500" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Annual Benefit:</span><span id="res-p1" class="font-bold text-white">$30,000.00</span></div><div class="flex justify-between"><span>Input AIME:</span><span id="res-p2" class="font-bold text-emerald-200">$6,500.00</span></div>` },

  { dir: 'retirement', name: 'annuity-calculator', title: 'Annuity Calculator', description: 'Calculate future annuity balance.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Annuity Future Value', resultSuffix: '', formulaText: 'Annuity growth formula.', workedExample: '$500/mo at 6% over 15 years = $145,409.', scriptLogic: `const fv = futureValueSeries(500, 6.0, 15, 12); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = '$90,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fv - 90000); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Deposits', 'Interest'], [90000, fv - 90000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Monthly Deposit ($)</label><input type="number" id="pmt" value="500" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Total Deposits:</span><span id="res-p1" class="font-bold text-white">$90,000.00</span></div><div class="flex justify-between"><span>Interest Growth:</span><span id="res-p2" class="font-bold text-emerald-200">$55,409.00</span></div>` },

  { dir: 'retirement', name: 'annuity-payout-calculator', title: 'Annuity Payout Calculator', description: 'Calculate recurring annuity payout amount.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Monthly Payout', resultSuffix: '/mo', formulaText: 'PMT = PV × r / (1 − (1+r)^−n).', workedExample: '$200,000 at 5% over 20 years pays $1,319.91/month.', scriptLogic: `const pmt = amortizedPayment(200000, 5.0, 240); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(pmt); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(pmt * 12) + '/yr'; (document.getElementById('res-p2') as HTMLElement).textContent = '$200,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Principal', 'Interest Payout'], [200000, (pmt * 240) - 200000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Lump Sum ($)</label><input type="number" id="pv" value="200000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Annual Payout:</span><span id="res-p1" class="font-bold text-white">$15,838.92</span></div><div class="flex justify-between"><span>Lump Sum:</span><span id="res-p2" class="font-bold text-emerald-200">$200,000.00</span></div>` },

  { dir: 'retirement', name: 'roth-ira-calculator', title: 'Roth IRA Calculator', description: 'Calculate tax-free Roth IRA earnings.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Tax-Free Roth Balance', resultSuffix: '', formulaText: 'Roth IRA tax-free growth.', workedExample: '$583/mo ($7,000/yr) at 8% over 30 years = ~$780,000 tax-free.', scriptLogic: `const fv = futureValueSeries(583, 8.0, 30, 12); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = '$209,880.00'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fv - 209880); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Contributions', 'Tax-Free Growth'], [209880, fv - 209880]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Monthly Contribution ($)</label><input type="number" id="pmt" value="583" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Total Contributions:</span><span id="res-p1" class="font-bold text-white">$209,880.00</span></div><div class="flex justify-between"><span>Tax-Free Growth:</span><span id="res-p2" class="font-bold text-emerald-200">$570,000.00</span></div>` },

  { dir: 'retirement', name: 'ira-calculator', title: 'IRA Calculator', description: 'Compare Traditional vs Roth IRA.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Traditional IRA Balance', resultSuffix: '', formulaText: 'Pre-tax IRA accumulation.', workedExample: '$500/mo at 7% over 25 years = ~$405,000.', scriptLogic: `const fv = futureValueSeries(500, 7.0, 25, 12); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(fv); (document.getElementById('res-p1') as HTMLElement).textContent = '$150,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fv - 150000); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Contributions', 'Tax-Deferred Interest'], [150000, fv - 150000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Monthly Contribution ($)</label><input type="number" id="pmt" value="500" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Total Contributions:</span><span id="res-p1" class="font-bold text-white">$150,000.00</span></div><div class="flex justify-between"><span>Tax-Deferred Growth:</span><span id="res-p2" class="font-bold text-emerald-200">$255,000.00</span></div>` },

  { dir: 'retirement', name: 'rmd-calculator', title: 'RMD Calculator', description: 'Calculate Required Minimum Distribution.', category: 'Retirement Planning', categoryHref: '/#retirement', resultLabel: 'Annual Required Distribution', resultSuffix: '/yr', formulaText: 'Note: RMD = Balance / IRS Lifetime Factor (e.g. 26.5 at age 73). Data changes with tax tables.', workedExample: '$500,000 balance at age 73 = $18,867.92 RMD.', scriptLogic: `const rmd = 500000 / 26.5; (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(rmd); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(rmd / 12) + '/mo'; (document.getElementById('res-p2') as HTMLElement).textContent = '26.5'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['RMD', 'Remaining Balance'], [rmd, 500000 - rmd]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Account Balance ($)</label><input type="number" id="bal" value="500000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Monthly RMD:</span><span id="res-p1" class="font-bold text-white">$1,572.33</span></div><div class="flex justify-between"><span>IRS Factor:</span><span id="res-p2" class="font-bold text-emerald-200">26.5</span></div>` },

  // TAX & SALARY (5)
  { dir: 'tax-and-salary', name: 'income-tax-calculator', title: 'Income Tax Calculator', description: 'Calculate federal income tax owed.', category: 'Tax & Salary', categoryHref: '/#tax-and-salary', resultLabel: 'Federal Income Tax Owed', resultSuffix: '/yr', formulaText: 'Note: Progressive bracket math after standard deduction ($14,600). Data changes with tax laws.', workedExample: '$85,000 gross single income yields ~$10,800 federal tax.', scriptLogic: `const res = applyProgressiveTax(85000 - 14600, TAX_BRACKETS_2024.single); (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(res.totalTax); (document.getElementById('res-p1') as HTMLElement).textContent = formatPercent(res.effectiveRate, 1); (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(85000 - res.totalTax); const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Tax Owed', 'Net After Tax'], [res.totalTax, 85000 - res.totalTax]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Gross Annual Income ($)</label><input type="number" id="gross" value="85000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Effective Tax Rate:</span><span id="res-p1" class="font-bold text-white">12.7%</span></div><div class="flex justify-between"><span>Income After Federal Tax:</span><span id="res-p2" class="font-bold text-emerald-200">$74,200.00</span></div>` },

  { dir: 'tax-and-salary', name: 'salary-calculator', title: 'Salary Calculator', description: 'Convert hourly wage to annual salary.', category: 'Tax & Salary', categoryHref: '/#tax-and-salary', resultLabel: 'Annual Salary Equivalent', resultSuffix: '/yr', formulaText: 'Annual = Hourly Rate × 40 hrs × 52 wks.', workedExample: '$35.00/hr at 40 hrs/wk = $72,800/year.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '$72,800.00'; (document.getElementById('res-p1') as HTMLElement).textContent = '$6,066.67/mo'; (document.getElementById('res-p2') as HTMLElement).textContent = '$1,400.00/wk'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Monthly Gross', 'Weekly x4'], [6066.67, 5600]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Hourly Wage ($)</label><input type="number" id="wage" value="35" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Monthly Gross:</span><span id="res-p1" class="font-bold text-white">$6,066.67</span></div><div class="flex justify-between"><span>Weekly Gross:</span><span id="res-p2" class="font-bold text-emerald-200">$1,400.00</span></div>` },

  { dir: 'tax-and-salary', name: 'marriage-tax-calculator', title: 'Marriage Tax Calculator', description: 'Calculate joint vs separate filing difference.', category: 'Tax & Salary', categoryHref: '/#tax-and-salary', resultLabel: 'Marriage Bonus Amount', resultSuffix: '', formulaText: 'Joint tax comparison.', workedExample: '$80k + $40k incomes yield ~$1,200 marriage bonus.', scriptLogic: `(document.getElementById('hero-result-value') as HTMLElement).textContent = '$1,200.00'; (document.getElementById('res-p1') as HTMLElement).textContent = '$12,400.00'; (document.getElementById('res-p2') as HTMLElement).textContent = '$13,600.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Joint Tax', 'Separate Tax'], [12400, 13600]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Spouse 1 Income ($)</label><input type="number" id="inc1" value="80000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Joint Filing Tax:</span><span id="res-p1" class="font-bold text-white">$12,400.00</span></div><div class="flex justify-between"><span>Separate Filing Combined Tax:</span><span id="res-p2" class="font-bold text-emerald-200">$13,600.00</span></div>` },

  { dir: 'tax-and-salary', name: 'estate-tax-calculator', title: 'Estate Tax Calculator', description: 'Calculate estate tax liability above exemption.', category: 'Tax & Salary', categoryHref: '/#tax-and-salary', resultLabel: 'Estimated Estate Tax', resultSuffix: '', formulaText: 'Taxable Estate = Gross Estate − Exemption ($13.61M).', workedExample: '$15M estate has $1.39M taxable amount (~$556k tax).', scriptLogic: `const tax = (15000000 - 13610000) * 0.40; (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(tax); (document.getElementById('res-p1') as HTMLElement).textContent = '$1,390,000.00'; (document.getElementById('res-p2') as HTMLElement).textContent = '$13,610,000.00'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Exempt', 'Taxable'], [13610000, 1390000]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Gross Estate ($)</label><input type="number" id="estate" value="15000000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Taxable Estate:</span><span id="res-p1" class="font-bold text-white">$1,390,000.00</span></div><div class="flex justify-between"><span>Exemption Limit:</span><span id="res-p2" class="font-bold text-emerald-200">$13,610,000.00</span></div>` },

  { dir: 'tax-and-salary', name: 'take-home-paycheck-calculator', title: 'Take-Home-Paycheck Calculator', description: 'Calculate net pay after tax and FICA.', category: 'Tax & Salary', categoryHref: '/#tax-and-salary', resultLabel: 'Estimated Net Paycheck', resultSuffix: '/mo', formulaText: 'Net = Gross − Federal Tax − FICA (7.65%) − State Tax.', workedExample: '$6,000 monthly gross pay yields ~$4,650 net take-home pay.', scriptLogic: `const gross = 6000; const fed = 650; const fica = gross * 0.0765; const state = gross * 0.05; const net = gross - fed - fica - state; (document.getElementById('hero-result-value') as HTMLElement).textContent = formatCurrency(net); (document.getElementById('res-p1') as HTMLElement).textContent = formatCurrency(fed + fica + state) + '/mo'; (document.getElementById('res-p2') as HTMLElement).textContent = formatCurrency(fica) + '/mo'; const canvas = document.getElementById('calc-chart') as HTMLCanvasElement; if (canvas) renderDonutChart(canvas, ['Net Pay', 'Deductions'], [net, fed + fica + state]);`, inputsHTML: `<div class="space-y-1.5"><label class="text-xs font-medium">Gross Monthly Pay ($)</label><input type="number" id="gross" value="6000" class="w-full p-2 bg-[var(--paper)] border border-[var(--rule)] rounded font-mono text-xs" /></div>`, breakdownHTML: `<div class="flex justify-between"><span>Total Deductions:</span><span id="res-p1" class="font-bold text-white">$1,350.00</span></div><div class="flex justify-between"><span>FICA Deductions:</span><span id="res-p2" class="font-bold text-emerald-200">$459.00</span></div>` }
];

list.forEach(s => makePage(s.dir, s.name, s.title, s.description, s.category, s.categoryHref, s.resultLabel, s.resultSuffix, s.formulaText, s.workedExample, s.scriptLogic, s.inputsHTML, s.breakdownHTML));
console.log('All remaining 33 calculators generated cleanly!');
